title: '"Not Cool Ep 7: Lindsay Getschel on climate change and national security"'
original_url: '"https://zencastr.com/z/raRwm8J7"'
date_published: '2019-09-20'
host:
  name: Arielle Kahn
  affiliation: ''
guests:
- name: Lindsay Getchell
  affiliation: Stimson Center
  title: Former Researcher
  bio: Lindsay Getchell is a former researcher at the Stimson Center focusing on climate
    change and national security.
  expertise_areas:
  - Climate Change
  - National Security
  - Youth Engagement
synopsis: This episode explores the interplay between climate change and national
  security, highlighting how climate change acts as a threat multiplier. Lindsay Getchell
  shares insights from her work with the UN Security Council and her research on climate
  impacts in vulnerable regions.
key_topics:
- Climate Change as a Threat Multiplier
- Impact of Climate Change on National Security
- Youth Engagement in Climate Action
- '"Case Studies: Syria and the Caribbean"'
tags:
- Climate Change
- National Security
- Youth Activism
- UN Security Council
key_points:
- Climate change exacerbates existing insecurities, leading to greater instability.
- Droughts have historically led to food insecurity and migration, contributing to
  conflict.
- The US Department of Defense acknowledges climate change as a national security
  issue.
segments:
- title: Impact of Climate Change on Security
  summary: Lindsay explains how climate change acts as a threat multiplier, worsening
    existing vulnerabilities like poverty and food insecurity.
  key_quotes:
  - quote: Climate change will directly exacerbate underlying insecurities, which
      can then have an impact on the overall stability of a community or a country.
    speaker: Lindsay Getchell
    context: Discussion on how climate change affects national security.
- title: Climate-Induced Instability and Conflict
  summary: Discussion on historical examples of climate impacts on conflict, including
    the Syrian conflict and political unrest in Egypt.
  key_quotes:
  - quote: The 2010 drought in Egypt tripled bread prices and contributed to unrest.
    speaker: Lindsay Getchell
    context: Reference to the US fourth national climate assessment linked to unrest.
- title: Ocean-Related Climate Risks and Solutions
  summary: Highlighting research on Caribbean security threats due to climate change
    and illegal fishing.
  key_quotes:
  - quote: We are developing a climate and ocean risk vulnerability index.
    speaker: Lindsay Getchell
    context: Description of the ongoing project assessing vulnerabilities in coastal
      regions.
- title: Youth Activism and Climate Policy
  summary: Emphasis on the importance of youth engagement in climate action and voting.
  key_quotes:
  - quote: '"If young people recognize the importance of voting, that''s one of the
      most impactful ways to have your voice heard."'
    speaker: Lindsay Getchell
    context: Discussion on the significance of youth participation in democracy.
websites_referenced:
- url: ''
  name: ''
  context: ''
  access_date: null
tools_mentioned:
- name: Climate and Ocean Risk Vulnerability Index
  url: ''
  description: A tool under development to assess vulnerability in coastal urban centers.
  context: This index aims to quantify the risks faced by these areas due to climate
    change.
research_papers:
- title: Fourth National Climate Assessment
  authors:
  - US Government
  year: 2018
  url: ''
  key_findings: Links between climate change impacts and social unrest in Syria and
    Egypt.
  context: This assessment highlights the security implications of climate change.
books_referenced:
- title: ''
  authors: []
  year: null
  isbn: ''
  context: ''
organizations:
  academic_institutions:
  - name: London School of Economics
    location: London, UK
    context: Where Lindsay studied the impacts of climate change on conflict.
  companies:
  - name: ''
    industry: ''
    context: ''
  non_profits:
  - name: The Nature Conservancy
    focus_area: Ecosystem-based adaptation to climate change
    context: Working on conservation projects in Jamaica.
  government_agencies:
  - name: US Department of Defense
    country: USA
    context: Recognizes climate change as a national security issue.
notable_people:
  academics:
  - name: Lindsay Getchell
    institution: Stimson Center
    field: Climate and Security
    context: Expert in the intersections of climate change and national security.
  industry_leaders:
  - name: James Mattis
    company: US Department of Defense
    role: Former Secretary of Defense
    context: Acknowledged the impacts of climate change on stability.
  policy_makers:
  - name: ''
    role: ''
    organization: ''
    context: ''
projects_mentioned:
- name: Climate and Ocean Risk Vulnerability Index
  organization: Stimson Center
  description: Index assessing vulnerability in Caribbean coastal urban centers.
  status: Ongoing
  url: ''
  context: Aimed at understanding climate risks and supporting resilience-building
    efforts.
events:
  historical:
  - name: Arab Spring Protests
    date: 2011
    significance: Rising unrest attributed in part to climate-induced agricultural
      collapse.
    context: Linked to migrations caused by drought.
  - name: US Fourth National Climate Assessment
    date: 2018
    significance: Provided evidence of climate change driving socio-economic unrest.
    context: A critical study linking environmental change to political instability.
  upcoming:
  - name: UN Climate Summit
    date: '2019-09-24'
    location: New York City, NY
    description: Discussion on municipal impacts of climate change.
    url: ''
keywords:
- Climate Change
- National Security
- Youth Activism
categories:
- Climate Policy
- Sustainability
- Public Engagement
intended_audience: Individuals interested in climate change, policy, and youth activism.
expertise_level: Beginner to Intermediate
recommended_reading:
- title: ''
  url: ''
  type: ''
  relevance: ''
action_items:
- Educate oneself about climate change impacts.
- Encourage youth advocacy and participation in voting.
controversial_topics:
- topic: Recognition of Climate Change as a Security Threat
  different_viewpoints:
  - perspective: Climate change is a significant threat to global stability.
    proponents: Lindsay Getchell, UN Security Council advocates.
    key_arguments: Climate exacerbates existing socio-economic tensions leading to
      conflicts.
  - perspective: Climate change disputes and its classification in security discussions.
    proponents: Skeptics within political realms.
    key_arguments: Concerns about prioritizing climate over other pressing security
      issues.
